- lib/client.js
- test/client/client_instance.test.js
Typically a revocation call does not have a response body and the current `successHandler` attempts to parse the response body and return it, resulting in `unexpected end of json input` error.
Fix that negates parsing the body if it’s not present.
> prevent revoke unexpected eof error

- lib/passport_strategy.js
- test/passport/passport_strategy.test.js
PR to address the issue I opened earlier. Added 1 new test and all others continue to pass. Thank you and let me know if I missed anything.
> Allow session key to be specified in passport strategy options

- lib/client.js
- lib/passport_strategy.js
We were expecting the wrong value in the issuer field and debugging was a little hard because the error message had the expected and actual values the wrong way around. This should swap them back.
> Fix error reporting in issuer field

- README.md
- lib/http.js
- lib/http_request.js
- lib/issuer.js
- package.json
- test/client/client_instance.test.js
- test/client/discover_client.test.js
- test/client/register_client.test.js
- test/issuer/discover_issuer.test.js
- test/issuer/discover_webfinger.test.js
- test/issuer/issuer_instance.test.js
- test/passport/passport_strategy.test.js
Because of the lightweight nature of got library the client will not use
environment-defined http(s) proxies. In order to have them used you'll need to either provide your own http request
implementation using the provided `httpClient` setter or use the bundled request
one.
Custom implementation:
```js
/*
* url {String}
* options {Object}
* options.headers {Object}
* options.body {String|Object}
* options.form {Boolean}
* options.query {Object}
* options.timeout {Number}
* options.retries {Number}
* options.followRedirect {Boolean}
*/
Issuer.httpClient = {
get(url, options) {}, // return Promise
post(url, options) {}, // return Promise
HTTPError, // used error constructor
};
```
Bundled (and maintained + tested) request implementation after you've added request
to your package.json …
> proxy settings / use request instead of got

- lib/client.js
- test/client/client_instance.test.js
Query parameters on `authorization_endpoint` defined on Issuer were ignored when forming `authorizationUrl`.
> Support for query parameters in defined authorization endpoint

- lib/client.js
- test/client/client_instance.test.js
The purpose of this PR is to fix compliance with [rfc6749 2.3.1](https://tools.ietf.org/html/rfc6749#section-2.3.1), specifically [Appendix B](https://tools.ietf.org/html/rfc6749#appendix-B). 
This library currently implements the Basic authentication scheme, but not the additional requirement of url-encoding both the username and password portion before base64 encoding the whole thing. 
There was a recent [fix](https://github.com/IdentityServer/IdentityServer4/issues/2039) in IdentityServer4 that prompted the discovery of this issue.
A similar implementation can be found [here](https://github.com/lelylan/simple-oauth2/blob/master/lib/encoding.js).
> fix basic auth to conform with rfc6749 2.3.1

- types/index.d.ts
As discussed in https://github.com/panva/node-oidc-provider/issues/623
> Allow 'id_token token' as a response type

- types/index.d.ts
Some helpful properties were missing in the types.
> fix(typescript): add missing types

- README.md
- docs/README.md
- lib/client.js
- lib/device_flow_handle.js
- lib/helpers/client.js
- lib/helpers/request.js
- test/client/dpop.test.js
- types/index.d.ts
- types/openid-client-tests.ts
Private Key to sign a DPoP Proof JWT with can now be passed to:
- client.callback()
- client.oauthCallback()
- client.refresh()
- client.grant()
- client.userinfo()
- client.requestResource()
- client.deviceAuthorization()
This is an IETF draft implementation with a once in a process warning
and breaking changes to the draft implementation will be shipped as
minor library versions.
> feat: OAuth 2.0 DPoP in various relevant API interfaces

- docs/README.md
The parameter structure has changed due to the got major version upgrade
which was not yet reflected in the documented example.
> docs: fix HTTP debugging example

- docs/README.md
Changed in https://github.com/panva/node-openid-client/commit/56f9fe7171ccc1bec6427d4f9bc45e419150ab4d
> docs: PKCE is used by default in passport strategy now

- docs/README.md
- lib/client.js
- test/client/client_instance.test.js
This PR has only 1 true fix: in the doc of https://github.com/panva/node-openid-client/blob/master/docs/README.md#clientuserinfoaccesstoken-options
The other substitutions have been done for consistency. The substitution in the error message is debatable, but code should not rely on error messages, error messages are not an API. I can delete this change if you want though 🙂
> Replace leftover deprecated "verb" with "method"

- lib/passport_strategy.js
- test/passport/passport_strategy.test.js
- types/index.d.ts
Currently the Strategy does not support client assertions making it troublesome to use with Passport.
Pass option `extras: CallbackExtras` to the `StrategyOptions` interface like so:
```
const strategy = new Strategy({
client,
params: {
scope: 'openid profile',
},
extras: {
clientAssertionPayload: {
aud: metadata.issuer
}
}
}, (tokenSet: TokenSet, done: (_err: any, _user?: any) => void) => {
done(null, tokenSet)
});
```
The function `OpenIDConnectStrategy.prototype.authenticate` is changed to include the `client._extras` as the last parameter to `client.callback`
> feat: add callback extras to strategy options

- types/index.d.ts
- types/openid-client-tests.ts
By using generics, we can enforce proper type checking without the need of casting. This is just the first, because `[key: string]: unknown` is used some more in the type declarations.
> feat(typescript): add userinfo response generics

- docs/README.md
- lib/device_flow_handle.js
- test/client/device_flow.test.js
Example using AbortController.
```js
const ac = new AbortController()
setTimeout(() => ac.abort(), 10000)
try {
await handle.poll({ signal: ac.signal })
} catch (err) {
console.log(err)
}
```
Example using handle.abort().
```js
setTimeout(() => handle.abort(), 10000)
try {
await handle.poll({ signal: ac.signal })
} catch (err) {
console.log(err)
}
```
resolves #355
closes #356
> feat: add abort control over Device Flow Handle polling

- types/index.d.ts
Adding `sub` and `nbf` to IntrospectionResponse type to match RFC7662 top-level members.
`scope` really should be optional here, but that would be a breaking change so leaving as-is.
> Fix #397 - Add remaining properties from RFC7662 to IntrospectionResponse typedef

- README.md
- lib/client.js
- lib/helpers/generators.js
- lib/helpers/request.js
- test/client/dpop.test.js
Fixes #406 
According to draft-03 of DPoP:
```
When the DPoP proof is used in conjunction with the presentation of
an access token, see Section 7, the DPoP proof also contains the
following claim:
*  "ath": hash of the access token (REQUIRED).  The value MUST be the
result of a base64url encoding (with no padding) the SHA-256 hash
of the ASCII encoding of the associated access token's value.
```
The DPoP implementation in this repository currently does not provide the `ath` claim when used with an access token (e.g., in `userinfo()` and `requestResource()`).  This PR updates the DPoP proof construction code so that if an access token is provided, then the `ath` parameter is included in the proof.
> Populate 'ath' claim in DPoP when access token is used

- lib/helpers/issuer.js
- test/client/client_instance.test.js
- test/issuer/issuer_instance.test.js
Adding application/jwk-set+json as an accepted header, since some OIDC providers are stricter and will return a 406 error code otherwise.
> #466 adding application/jwk-set+json for JWTS calls

- types/index.d.ts
I was recently writing some tests for handling errors from `openid-client` and while attempting to instantiate one of the errors, I noticed that the constructor types don't match the implementation.
Since [the types don't explicitly declare a `constructor`](https://github.com/panva/node-openid-client/blob/3adf1a47b5267f7ce20a7c0c29e7207c0ddf34ca/types/index.d.ts#L567-L589), they inherit they inherit it from `Error`, which doesn't match [their overloaded constructors](https://github.com/panva/node-openid-client/blob/3adf1a47b5267f7ce20a7c0c29e7207c0ddf34ca/lib/errors.js#L4).
So, I tried adding what I think are roughly the correct constructor types for the `OPError` and `RPError` classes. I saw that there is a `openid-client-tests.ts` file, so let me know if there's anything additional I …
> Add types for error constructors

- docs/README.md
@panva: When searching the repo for a solution to `JWT not active yet`, the relevant docs did not appear in the search results. #454 did appear, which has a link to the appropriate docs, but this pull request makes the docs a little more discoverable by including the relevant error message.
> docs: update clock tolerance text

- docs/README.md
- lib/passport_strategy.js
@panva: As discussed, this pull request ignores static `state` and `nonce` values that are passed to the `Strategy()` (a mis-use of the API). Ignoring them here allows them to be dynamically generated on each `authenticate()` for flows that require them.
I also documented how to pass dynamic parameters to `authenticate()` (in a separate commit, daa70a5, in case you aren't interested in this change).
Note that this is a breaking change for users who are mis-using the API in this way if their Authorization Server requires a nonce or state for a flow where the spec does not require it.
Let me know if tests or anything else would be helpful.
> fix(passport): ignore static state and nonce passed to Strategy()

- lib/helpers/client.js
- test/client/client_instance.test.js
Implementation of https://github.com/panva/node-openid-client/issues/609
> fix: handle empty client_secret with basic and post client auth

- lib/client.js
- test/client/client_instance.test.js
I worked on the issue https://github.com/panva/node-openid-client/issues/626
> fix: consistent space encoding in authorizationUrl

- lib/issuer.js
Just splits uri detection code from a call to discovery endpoint and avoids duplication
> refactor: issuer discovery

- README.md
- docs/README.md
As for the headline: names like "client credentials flow" "client credentials grant" and "client credentials grant flow" are flying around. I just went with the latter, idk.
> Add client credentials flow example to readme

- lib/helpers/issuer.js
When this library is run under environments which prohibit use of the deprecated `__proto__` getter/setter, it may cause a crash due to reading from the __proto__ property. An example scenario is when the `--disable-proto=throw` flag is used for NodeJS.
To disable consideration of the `prototype`, `__proto__`, and `constructor` fields fields when hashing, the `respectType` flag can be toggled off. This is not a problem for this library, as we are querying only for the existence of a object created via an object literal, which will have these properties all the same anyway.
> refactor: avoid use of prototype attributes in keystore queries
